### ISSUE TITLE
Make EasySNMPNoSuchObjectError exception optional

### ISSUE THREAD

**Issue by nnathan** [fgimian/easysnmp#16]
I'm running the following script:

```python
#!/usr/bin/python

import easysnmp
oids = [
    '1.3.6.1.4.1.2021.13.15.1.1.6.15',
    '1.3.6.1.2.1.31.1.1.1.7.3',
    '1.3.6.1.2.1.11.5.0',
    '1.3.6.1.4.1.2021.11.55.0',
    '1.3.6.1.4.1.2021.13.15.1.1.6.13',
    '1.3.6.1.2.1.11.16.0',
    '1.3.6.1.4.1.2021.11.60.0',
    '1.3.6.1.4.1.2021.10.1.5.2',
    '1.3.6.1.4.1.2021.13.15.1.1.5.8',
    '1.3.6.1.4.1.2021.13.15.1.1.5.9',
    '1.3.6.1.4.1.4502.1.11.101.1',
    '1.3.6.1.2.1.11.13.0',
    '1.3.6.1.4.1.2021.13.15.1.1.6.11',
    '1.3.6.1.2.1.11.14.0',
    '1.3.6.1.4.1.2021.13.15.1.1.5.1',
    '1.3.6.1.4.1.2021.13.15.1.1.5.2',
    '1.3.6.1.4.1.2021.13.15.1.1.5.3',
    '1.3.6.1.4.1.2021.13.15.1.1.5.4',
    '1.3.6.1.4.1.2021.13.15.1.1.5.5',
    '1.3.6.1.4.1.2021.11.58.0'
]

values = easysnmp.easy.snmp_get(
    oids,
    hostname='10.255.30.133',
    version=2,
    community='public'
)
```

I get the following error:
```bash
$ python test_snmp.py
Traceback (most recent call last):
  File "test_snmp.py", line 31, in <module>
    community='enf0r5er'
  File "/srv/virtualenvs/bpl-poll-consumer/local/lib/python2.7/site-packages/easysnmp/easy.py", line 22, in snmp_get
    return session.get(oids)
  File "/srv/virtualenvs/bpl-poll-consumer/local/lib/python2.7/site-packages/easysnmp/session.py", line 308, in get
    validate_results(varlist)
  File "/srv/virtualenvs/bpl-poll-consumer/local/lib/python2.7/site-packages/easysnmp/session.py", line 73, in validate_results
    raise EasySNMPNoSuchObjectError('no such object could be found')
```

For shits and giggles, here is the `tcpdump`:
```bash
$ sudo tcpdump -ni eth0 host 10.255.30.133
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 65535 bytes
14:41:35.440681 IP 10.183.23.54.40022 > 10.255.30.133.161:  C=public GetRequest(361)  .1.3.6.1.4.1.2021.13.15.1.1.6.15 .1.3.6.1.2.1.31.1.1.1.7.3 .1.3.6.1.2.1.11.5.0 .1.3.6.1.4.1.2021.11.55.0 .1.3.6.1.4.1.2021.13.15.1.1.6.13 .1.3.6.1.2.1.11.16.0 .1.3.6.1.4.1.2021.11.60.0 .1.3.6.1.4.1.2021.10.1.5.2 .1.3.6.1.4.1.2021.13.15.1.1.5.8 .1.3.6.1.4.1.2021.13.15.1.1.5.9 .1.3.6.1.4.1.4502.1.11.101.1 .1.3.6.1.2.1.11.13.0 .1.3.6.1.4.1.2021.13.15.1.1.6.11 .1.3.6.1.2.1.11.14.0 .1.3.6.1.4.1.2021.13.15.1.1.5.1 .1.3.6.1.4.1.2021.13.15.1.1.5.2 .1.3.6.1.4.1.2021.13.15.1.1.5.3 .1.3.6.1.4.1.2021.13.15.1.1.5.4 .1.3.6.1.4.1.2021.13.15.1.1.5.5 .1.3.6.1.4.1.2021.11.58.0
14:41:35.455465 IP 10.255.30.133.161 > 10.183.23.54.40022:  C=public GetResponse(393)  .1.3.6.1.4.1.2021.13.15.1.1.6.15=0 .1.3.6.1.2.1.31.1.1.1.7.3=104046 .1.3.6.1.2.1.11.5.0=0 .1.3.6.1.4.1.2021.11.55.0=0 .1.3.6.1.4.1.2021.13.15.1.1.6.13=0 .1.3.6.1.2.1.11.16.0=88 .1.3.6.1.4.1.2021.11.60.0=1896669006 .1.3.6.1.4.1.2021.10.1.5.2=356 .1.3.6.1.4.1.2021.13.15.1.1.5.8=0 .1.3.6.1.4.1.2021.13.15.1.1.5.9=0 .1.3.6.1.4.1.4502.1.11.101.1=[noSuchObject] .1.3.6.1.2.1.11.13.0=8923579 .1.3.6.1.4.1.2021.13.15.1.1.6.11=0 .1.3.6.1.2.1.11.14.0=0 .1.3.6.1.4.1.2021.13.15.1.1.5.1=0 .1.3.6.1.4.1.2021.13.15.1.1.5.2=0 .1.3.6.1.4.1.2021.13.15.1.1.5.3=0 .1.3.6.1.4.1.2021.13.15.1.1.5.4=0 .1.3.6.1.4.1.2021.13.15.1.1.5.5=0 .1.3.6.1.4.1.2021.11.58.0=2176755532
```

Since the SNMP agent responds, the easysnmp interface should respond to the application with a way to identify which OIDs return noSuchObject, rather than raise an exception.

**Comment by fgimian** [comment]
This behaviour is now available via the `abort_on_nonexistent` kwarg, closing.
