### ISSUE TITLE
ImportError: cannot import name interface

### ISSUE THREAD

**Issue by pydrive** [fgimian/easysnmp#42]
Hi everyone! I have a trouble with easysnmp. The example above is using easysnmp installed with pip:
```bash
(snmp) ⋊> ~/sandbox snmpget -V                                          19:35:44
NET-SNMP version: 5.7.3
(snmp) ⋊> ~/sandbox python                                              19:35:52
Python 2.7.11 (default, Jan 22 2016, 08:28:37)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import easysnmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/denis/env/snmp/lib/python2.7/site-packages/easysnmp/__init__.py", line 1, in <module>
    from .easy import (  # noqa
  File "/Users/denis/env/snmp/lib/python2.7/site-packages/easysnmp/easy.py", line 3, in <module>
    from .session import Session
  File "/Users/denis/env/snmp/lib/python2.7/site-packages/easysnmp/session.py", line 8, in <module>
    from . import interface
ImportError: dlopen(/Users/denis/env/snmp/lib/python2.7/site-packages/easysnmp/interface.so, 2): Symbol not found: _netsnmp_transport_config_compare
  Referenced from: /Users/denis/env/snmp/lib/python2.7/site-packages/easysnmp/interface.so
  Expected in: flat namespace
 in /Users/denis/env/snmp/lib/python2.7/site-packages/easysnmp/interface.so
```

And some test results

```bash
/Users/denis/env/containers/bin/python "/Applications/PyCharm CE.app/Contents/helpers/pycharm/pytestrunner.py" -p pytest_teamcity /Users/denis/sandbox/easysnmp/tests/test_session_build_varlist.py
Testing started at 19:28 ...
Test session starts (platform: darwin, Python 2.7.11, pytest 2.9.1, pytest-sugar 0.7.1)
rootdir: /Users/denis/sandbox/easysnmp, inifile: setup.cfg
plugins: cov-2.2.1, flake8-0.4, sugar-0.7.1

――――――――――――― ERROR collecting tests/test_session_build_varlist.py ―――――――――――――
/Users/denis/sandbox/easysnmp/tests/test_session_build_varlist.py:3: in <module>
    from easysnmp.session import build_varlist
/Users/denis/sandbox/easysnmp/easysnmp/__init__.py:1: in <module>
    from .easy import (  # noqa
/Users/denis/sandbox/easysnmp/easysnmp/easy.py:3: in <module>
    from .session import Session
/Users/denis/sandbox/easysnmp/easysnmp/session.py:8: in <module>
    from . import interface
E   ImportError: cannot import name interface

 tests/test_session_build_varlist.py ✓                           100% ██████████

--------------- coverage: platform darwin, python 2.7.11-final-0 ---------------
Name                                                 Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------
/Users/denis/sandbox/easysnmp/easysnmp/__init__.py       4      3    25%   5-11
/Users/denis/sandbox/easysnmp/easysnmp/easy.py          20     18    10%   6-121
/Users/denis/sandbox/easysnmp/easysnmp/session.py      131    126     4%   10-478
----------------------------------------------------------------------------------
TOTAL                                                  155    147     5%   

Results (0.19s):
       1 passed
```

This traceback occurred after I installed easysnmp manually from github sources 
```bash
(snmp) ⋊> ~/s/easysnmp on master ⨯ python                                           19:39:00
Python 2.7.11 (default, Jan 22 2016, 08:28:37)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import easysnmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "easysnmp/__init__.py", line 1, in <module>
    from .easy import (  # noqa
  File "easysnmp/easy.py", line 3, in <module>
    from .session import Session
  File "easysnmp/session.py", line 8, in <module>
    from . import interface
ImportError: cannot import name interface
>>>
```
Mac OS X 10.10.5
Can you say what I do incorrect?

**Comment by kamakazikamikaze** [comment]
It looks like you're using VirtualEnv? Perhaps you're experiencing the same problem as with #38

**Comment by pydrive** [comment]
Thank you for reply. Yes, I`m using virtualenv, but i have the same problem without using it with easysnmp installed globally. Here is the new traceback above
```bash
^^>>> python                                                            22:54:27
Python 2.7.11 (default, Jan 22 2016, 08:29:18)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import easysnmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/easysnmp/__init__.py", line 1, in <module>
    from .easy import (  # noqa
  File "/usr/local/lib/python2.7/site-packages/easysnmp/easy.py", line 3, in <module>
    from .session import Session
  File "/usr/local/lib/python2.7/site-packages/easysnmp/session.py", line 8, in <module>
    from . import interface
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/easysnmp/interface.so, 2): Symbol not found: _netsnmp_transport_config_compare
  Referenced from: /usr/local/lib/python2.7/site-packages/easysnmp/interface.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/easysnmp/interface.so
```

**Comment by kamakazikamikaze** [comment]
That last error (`Symbol not found: _netsnmp_transport_config_compare`) is the exact same from that issue, so it may be a linking error.

I'll move over to OS X today and take a look on what needs to be done to fix it. Hopefully I can get back to you later with a solution, or at least a report of some progress.

**Comment by pydrive** [comment]
Thank you so much, this issue was tested on three macs with/without virtualenv, but result was the same

**Comment by kamakazikamikaze** [comment]
Could you use `otool -L` and post the output in the other issue thread? I'd like to move the conversation over to there so that we can resolve everything in one place

**Comment by kamakazikamikaze** [comment]
So I found a few things, primarily that my VirtualEnv was not pointed to the correct GCC (had to `export CC=/usr/bin/gcc`). After doing so I could compile and install the package just fine. However, (i)python would also show the import errors. I then realized that because I was actually `cd`'d into the easysnmp repo itself, so the interpreter assumed that I was wanting to import the *local* module, which does not exist because it must be compiled as it is a C-extension. If I `cd`'d up one folder, I could import easysnmp without a problem.

**Comment by kamakazikamikaze** [comment]
Got it! (I think.) Unfortunately it requires manually changing the library paths. [See here for details.](http://superuser.com/questions/282450/where-do-i-set-dyld-library-path-on-mac-os-x-and-is-it-a-good-idea)

So, first I listed out the linked libraries:
```
(snmp) Kents-MacBook-Pro:SNMPBenchmark kentcoble$ otool -L /Users/kentcoble/Envs/snmp/lib/python2.7/site-packages/easysnmp/interface.so
/Users/kentcoble/Envs/snmp/lib/python2.7/site-packages/easysnmp/interface.so:
	/usr/lib/libnetsnmp.25.dylib (compatibility version 26.0.0, current version 26.2.0)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
```

libnetsnmp and libcrypto are out-of-date and are the targets. So, we need to use `install_name_tool` for both items. The syntax for this is `install_name_tool -change old_lib new_lib target`, as demonstrated:

```
(snmp) Kents-MacBook-Pro:SNMPBenchmark kentcoble$ install_name_tool -change /usr/lib/libnetsnmp.25.dylib /usr/local/opt/net-snmp/lib/libnetsnmp.30.dylib /Users/kentcoble/Envs/snmp/lib/python2.7/site-packages/easysnmp/interface.so

(snmp) Kents-MacBook-Pro:SNMPBenchmark kentcoble$ otool -L /Users/kentcoble/Envs/snmp/lib/python2.7/site-packages/easysnmp/interface.so
/Users/kentcoble/Envs/snmp/lib/python2.7/site-packages/easysnmp/interface.so:
	/usr/local/opt/net-snmp/lib/libnetsnmp.30.dylib (compatibility version 26.0.0, current version 26.2.0)
	/usr/lib/libcrypto.0.9.8.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)

(snmp) Kents-MacBook-Pro:SNMPBenchmark kentcoble$ install_name_tool -change /usr/lib/libcrypto.0.9.8.dylib /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /Users/kentcoble/Envs/snmp/lib/python2.7/site-packages/easysnmp/interface.so

(snmp) Kents-MacBook-Pro:SNMPBenchmark kentcoble$ ipython
iWARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
mPython 2.7.11 (default, Dec 26 2015, 17:47:53) 
Type "copyright", "credits" or "license" for more information.

IPython 3.1.0 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: import easysnmp

In [2]: 
```

See if that works for you.

**Comment by kamakazikamikaze** [comment]
@pydrive I've made a new commit and hope that it will resolve this issue. Please keep an eye out for #43

**Comment by pydrive** [comment]
Thank you. I`ve made these steps, but i think that libnetsnmp isn`t linking to interface.so
```bash
(CoreEnv) denis at MacBook-Pro-Denis in /u/lib
» install_name_tool -change /usr/lib/libnetsnmp.25.dylib /usr/local/opt/net-snmp/lib/libnetsnmp.30.dylib /Users/denis/env/CoreEnv/lib/python2.7/site-packages/easysnmp/interface.so
(CoreEnv) denis at MacBook-Pro-Denis in /u/lib
» otool -L ~/env/CoreEnv/lib/python2.7/site-packages/easysnmp/interface.so
/Users/denis/env/CoreEnv/lib/python2.7/site-packages/easysnmp/interface.so:
	/usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 0.9.8, current version 0.9.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
(CoreEnv) denis at MacBook-Pro-Denis in /u/lib
```

**Comment by kamakazikamikaze** [comment]
Can you uninstall Easysnmp and reinstall using the [branch I made?](https://github.com/kamakazikamikaze/easysnmp/commit/44c62317dbd38b9f3bccf90fac9078b2434c00d9)

**Comment by pydrive** [comment]
Yes! It works! Thank you so much.

**Comment by kamakazikamikaze** [comment]
I wouldn't close this just yet since the master branch/current release does _not_ resolve this issue.

**Comment by sivabudh** [comment]
@kamakazikamikaze we are currently install easysnmp by putting this into our requirements.txt at the moment:

```
-e git+git://github.com/kamakazikamikaze/easysnmp.git@44c62317dbd38b9f3bccf90fac9078b2434c00d9#egg=easysnmp
```

Any chance you might be so kind as to publish a `0.2.5`, please? :)

**Comment by kamakazikamikaze** [comment]
@sivabudh I do not have permissions to edit this repository. I cannot publish a version nor add it to pip :( sorry

**Comment by sivabudh** [comment]
Got it, @kamakazikamikaze. I will try to maintain the project maintainer.

**Comment by tungd** [comment]
I managed to workaround this issue without installing from the fork. The cause seems to be the Homebrew installation lacks `net-snmp-config` script, which is used to determine the linker flags. (So this is macOS/Homebrew-only issue).

```
$ which net-snmp-config
/usr/bin/net-snmp-config

$ otool -L /Users/tung/Projects/***/env/lib/python3.5/site-packages/easysnmp/interface.cpython-35m-darwin.so
/Users/tung/Projects/**/env/lib/python3.5/site-packages/easysnmp/interface.cpython-35m-darwin.so:
	/usr/lib/libcrypto.35.dylib (compatibility version 36.0.0, current version 36.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```

My workaround:

```
$ PATH="$(brew --prefix net-snmp)/bin:$PATH" pip install easysnmp

$ otool -L /Users/tung/Projects/***/env/lib/python3.5/site-packages/easysnmp/interface.cpython-35m-darwin.so
/Users/tung/Projects/**/env/lib/python3.5/site-packages/easysnmp/interface.cpython-35m-darwin.so:
	/Users/tung/.local/opt/net-snmp/lib/libnetsnmp.30.dylib (compatibility version 31.0.0, current version 31.3.0)
	/Users/tung/.local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
```
