### ISSUE TITLE
installed easysnmp is not working

### ISSUE THREAD

**Issue by msuluhan** [fgimian/easysnmp#53]
Hello 

I have tried to install easysnmp to RHEL 6.7 server. I installed net-snmp 5.7.3 from source and then tried to install easysnmp with following log. As far as I could see I did not get error while the module's installation. But when I try to use  I got following errors

Could you help me about the issue?

Thanks
```
Python 2.6.6 (r266:84292, May 22 2015, 08:34:51)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from easysnmp import Session
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "easysnmp/__init__.py", line 1, in <module>
    from .easy import (  # noqa
  File "easysnmp/easy.py", line 3, in <module>
    from .session import Session
  File "easysnmp/session.py", line 8, in <module>
    from . import interface
ImportError: cannot import name interface



[root@max02 easysnmp-master]# python
Python 2.6.6 (r266:84292, May 22 2015, 08:34:51)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-15)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import easysnmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "easysnmp/__init__.py", line 1, in <module>
    from .easy import (  # noqa
  File "easysnmp/easy.py", line 3, in <module>
    from .session import Session
  File "easysnmp/session.py", line 8, in <module>
    from . import interface
ImportError: cannot import name interface


```
```
[root@max02 easysnmp-master]# python setup.py install
running install
running bdist_egg
running egg_info
writing easysnmp.egg-info/PKG-INFO
writing top-level names to easysnmp.egg-info/top_level.txt
writing dependency_links to easysnmp.egg-info/dependency_links.txt
reading manifest file 'easysnmp.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'easysnmp.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/easysnmp
copying build/lib.linux-x86_64-2.6/easysnmp/interface.so -> build/bdist.linux-x86_64/egg/easysnmp
copying build/lib.linux-x86_64-2.6/easysnmp/__init__.py -> build/bdist.linux-x86_64/egg/easysnmp
copying build/lib.linux-x86_64-2.6/easysnmp/session.py -> build/bdist.linux-x86_64/egg/easysnmp
copying build/lib.linux-x86_64-2.6/easysnmp/compat.py -> build/bdist.linux-x86_64/egg/easysnmp
copying build/lib.linux-x86_64-2.6/easysnmp/exceptions.py -> build/bdist.linux-x86_64/egg/easysnmp
copying build/lib.linux-x86_64-2.6/easysnmp/variables.py -> build/bdist.linux-x86_64/egg/easysnmp
copying build/lib.linux-x86_64-2.6/easysnmp/utils.py -> build/bdist.linux-x86_64/egg/easysnmp
copying build/lib.linux-x86_64-2.6/easysnmp/easy.py -> build/bdist.linux-x86_64/egg/easysnmp
copying build/lib.linux-x86_64-2.6/easysnmp/helpers.py -> build/bdist.linux-x86_64/egg/easysnmp
byte-compiling build/bdist.linux-x86_64/egg/easysnmp/__init__.py to __init__.pyc
byte-compiling build/bdist.linux-x86_64/egg/easysnmp/session.py to session.pyc
byte-compiling build/bdist.linux-x86_64/egg/easysnmp/compat.py to compat.pyc
byte-compiling build/bdist.linux-x86_64/egg/easysnmp/exceptions.py to exceptions.pyc
byte-compiling build/bdist.linux-x86_64/egg/easysnmp/variables.py to variables.pyc
byte-compiling build/bdist.linux-x86_64/egg/easysnmp/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/easysnmp/easy.py to easy.pyc
byte-compiling build/bdist.linux-x86_64/egg/easysnmp/helpers.py to helpers.pyc
creating stub loader for easysnmp/interface.so
byte-compiling build/bdist.linux-x86_64/egg/easysnmp/interface.py to interface.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying easysnmp.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying easysnmp.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying easysnmp.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying easysnmp.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/easysnmp-0.2.5_dev-py2.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing easysnmp-0.2.5_dev-py2.6-linux-x86_64.egg
removing '/usr/lib64/python2.6/site-packages/easysnmp-0.2.5_dev-py2.6-linux-x86_64.egg' (and everything under it)
creating /usr/lib64/python2.6/site-packages/easysnmp-0.2.5_dev-py2.6-linux-x86_64.egg
Extracting easysnmp-0.2.5_dev-py2.6-linux-x86_64.egg to /usr/lib64/python2.6/site-packages
easysnmp 0.2.5-dev is already the active version in easy-install.pth

Installed /usr/lib64/python2.6/site-packages/easysnmp-0.2.5_dev-py2.6-linux-x86_64.egg




[root@max02 easysnmp-master]# snmpget --version
NET-SNMP version: 5.7.3
[root@max02 easysnmp-master]#
```

**Comment by markliederbach** [comment]
Paging @kamakazikamikaze , I am also experiencing this. Can you enlighten us as to how we should be installing this package from source like this?

**Comment by ghost** [comment]
Try this:
`pip uninstall easysnmp`
`pip install git+https://github.com/kamakazikamikaze/easysnmp.git`

**Comment by markliederbach** [comment]
That works, but why? Sort of confusing that git works but a local install won't.

**Comment by ghost** [comment]
I believe it has to do with the dependencies. Easy SNMP is built on top of NET-SNMP. If you check your versions `snmpget --version` NET-SNMP may have changed.

**Comment by tpd001** [comment]
Similar experience, Python 3.6 / Miniconda / NetSNMP 5.7.3:

    (cenv) [collector@monitoring portal]$python3.6  
    Python 3.6.3 |Anaconda, Inc.| (default, Nov 20 2017, 20:41:42) 
    [GCC 7.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from easysnmp import Session
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/home/collector/miniconda3/lib/python3.6/site-packages/easysnmp/__init__.py", line 1, in <module>
    from .easy import (  # noqa
    File "/home/collector/miniconda3/lib/python3.6/site-packages/easysnmp/easy.py", line 3, in <module>
    from .session import Session
    File "/home/collector/miniconda3/lib/python3.6/site-packages/easysnmp/session.py", line 8, in <module>
    from . import interface
    ImportError: /home/collector/miniconda3/lib/python3.6/site-packages/easysnmp/interface.cpython-36m-x86_64-linux-gnu.so: undefined symbol: usmAESPrivProtocol
   >>> 

Note the interface.cpython-36m-x86_64-linux-gnu.so library does not have a dependency on libnetsnmp.so, which contains the symbol:

    (cenv) [collector@monitoring portal]$ldd /home/collector/miniconda3/lib/python3.6/site-packages/easysnmp/interface.cpython-36m-x86_64-linux-gnu.so 
    linux-vdso.so.1 =>  (0x00007fff3b7ff000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fda2432f000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fda23f9a000)
    /lib64/ld-linux-x86-64.so.2 (0x00000034c0400000)

    (cenv) [collector@monitoring portal]$nm -ng /usr/local/lib/libnetsnmp.so  | grep usmAESPrivProtocol
    00000000002a5b60 D usmAESPrivProtocol

Tracing this back to installation:

    (cenv) [collector@monitoring portal]$pip install easysnmp -v --no-cache-dir | more
    Collecting easysnmp
    ...
    /bin/sh: net-snmp-config: command not found   <====== 

Is there a reason 'pip install' does not fail at this point?

Thank you
Tim

**Comment by WhittlesJr** [comment]
This may not be helpful to anyone else, but I'll leave a breadcrumb:

I had the same issue trying to package this on NixOS. The solution was:

```nix
{
  postFixup = ''
    patchelf --add-needed ${pkgs.net_snmp}/lib/libnetsnmp.so "$out/${python.sitePackages}/easysnmp/"*cpython*.so
  '';
}
```

Again, it's only strictly useful for NixOS, but maybe it can give someone a hint if they run into the same problem packaging easysnmp on another distro.

**Comment by WhittlesJr** [comment]
Update: A simpler solution turned out to be using the `--basedir=` flag to specify the location of the `net-snmp-config` executable. (Which for me would be `${pkgs.net_snmp}/bin`)
