### ISSUE TITLE
OSX - flat namespace in /usr/local/lib/python2.7/site-packages/easysnmp/interface.so

### ISSUE THREAD

**Issue by ajwillo** [fgimian/easysnmp#56]
I can see a similar issue in this post here https://github.com/fgimian/easysnmp/issues/42 but I'm not sure if that same issues applies to me or not.

basically i have installs python via home-brew

```
alexs-mbp:~ alex$ which python
/usr/local/bin/python
alexs-mbp:~ alex$
```
and have install easysnmp via pip and net-snmp via home-brew

```
alexs-mbp:~alex$ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import easysnmp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/easysnmp/__init__.py", line 1, in <module>
    from .easy import (  # noqa
  File "/usr/local/lib/python2.7/site-packages/easysnmp/easy.py", line 3, in <module>
    from .session import Session
  File "/usr/local/lib/python2.7/site-packages/easysnmp/session.py", line 8, in <module>
    from . import interface
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/easysnmp/interface.so, 2): Symbol not found: _netsnmp_transport_config_compare
  Referenced from: /usr/local/lib/python2.7/site-packages/easysnmp/interface.so
  Expected in: flat namespace
 in /usr/local/lib/python2.7/site-packages/easysnmp/interface.so
```
I also get this message when using brew to check

```
 Warning: net-snmp is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
alexs-mbp:~ alex$ brew install net-snmp --force
Warning: net-snmp-5.7.3 already installed, it's just not linked.
alexs-mbp:~ alex$ 
```
i did a brew link which gives me the below

```
Warning: net-snmp is a keg-only and another version is linked to opt.
Use `brew install --force` if you want to install this version
alexs-mbp:~ alex$ brew install net-snmp --force
Warning: net-snmp-5.7.3 already installed, it's just not linked.
alexs-mbp:~ alex$ brew link net-snmp
Warning: net-snmp is keg-only and must be linked with --force
Note that doing so can interfere with building software.

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/net-snmp/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/net-snmp/sbin:$PATH"' >> ~/.bash_profile
alexs-mbp:~ alexwilloughby$ brew link net-snmp --force
Linking /usr/local/Cellar/net-snmp/5.7.3... 182 symlinks created

If you need to have this software first in your PATH instead consider running:
  echo 'export PATH="/usr/local/opt/net-snmp/bin:$PATH"' >> ~/.bash_profile
  echo 'export PATH="/usr/local/opt/net-snmp/sbin:$PATH"' >> ~/.bash_profile
alexs-mbp:~ alex$ 
```
starting python and importing easysnmp still gives me the same error does anyone know how to fix this?

Thanks

**Comment by ajwillo** [comment]
this fork seems to fix the issue
pip install git+https://github.com/kamakazikamikaze/easysnmp.git

**Comment by kamakazikamikaze** [comment]
@ajwillo Sorry for not seeing this earlier. Since that fork was created by me, please feel free to let me know about any issues you have with installing it!
